# Numpy 특강 part 3

----------

In [1]:
import numpy as np

In [2]:
np.info(np.sum)

 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same pr

## 0. shape, ndim?

### ndim:
https://numpy.org/devdocs/reference/generated/numpy.ndarray.ndim.html?highlight=ndim#numpy.ndarray.ndim

In [3]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a.shape

(4, 5)

In [5]:
a.ndim # ndim은 대괄호의 개수로 세면 파악하기 편합니다.

2

In [6]:
np.sum(a)

190

ndim에 대해 파악하는 방법

1> 대괄호 개수를 센다.

2> .shape에 나오는 숫자의 개수 (ex> shape = (2,)이면 ndim이 1)

3> .ndim을 사용한다.

In [7]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [8]:
b.shape

(5,)

In [9]:
b.ndim

1

-------

## 1. axis란?

### 1) np.sum(axis = 0)

1> 행이 고정된 채 원소들끼리 더해지는 연산

2> 연산 이후 shape은 행 부분이 없어진다.

In [10]:
a.shape

(4, 5)

In [11]:
a.ndim

2

In [12]:
np.sum(a, axis=0)

array([30, 34, 38, 42, 46])

In [13]:
np.sum(a, axis=0).shape

(5,)

In [14]:
np.sum(a, axis=0).ndim

1

### 2) np.sum(axis = 1)

1> 열이 고정된 채 원소들끼리 더해지는 연산

2> 연산 이후 shape은 열 부분이 없어진다.

In [15]:
np.sum(a, axis=1)

array([10, 35, 60, 85])

In [16]:
a.shape # (4,5) -> (4,)

(4, 5)

In [17]:
np.sum(a, axis=1).shape

(4,)

In [27]:
np.sum(a, axis=0).shape

(5,)

In [18]:
np.sum(a, axis=1).ndim

1

아쉬운 점: sum을 하면 차원이 줄어드는 현상이 벌어진다.
    
np.sum(a, axis=1) => array([10, 35, 60, 85])말고 

np.sum(a, axis=1) => array([[10],

                          [35],
                           
                          [60],
                           
                          [85]])  이렇게 나오면 좋을 것 같을 때 어떡할까?

------

## 2.keepdims

말 그대로 차원(dimension)이 유지(keep)되는 연산이다.

In [21]:
np.sum(a, axis=0, keepdims = False)
#np.sum(a, axis=0)

array([30, 34, 38, 42, 46])

In [22]:
np.sum(a, axis=0, keepdims = True)

array([[30, 34, 38, 42, 46]])

더 신기한 건 이 부분이다.

In [23]:
np.sum(a, axis=1, keepdims = False)

array([10, 35, 60, 85])

In [24]:
np.sum(a, axis=1, keepdims = True)

array([[10],
       [35],
       [60],
       [85]])

In [25]:
np.sum(a, axis=1, keepdims = True).ndim

2

In [26]:
np.sum(a, axis=1, keepdims = False).ndim

1

keepdims는 앞으로 딥러닝하면서 많이 나오는 내용은 아니지만

axis 개념은 빈출되는 내용이니 여러번 봐주시기 바랍니다.