# Numpy indexing & slicing

In [1]:
import numpy as np

--------

## 1. python 문법

3주차에 배웠던 np.arange와 비슷한 패턴이 반복됩니다.

처음 배울 때가 어렵지 초반에 일부 개념들을 확실히 익혀두면 점점 쉬워집니다.

In [2]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### 1) Indexing

**<font color="red"> [start] => start만** 

In [3]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [4]:
a[3][5]

23

### 2) slicing

#### 1> 기본 

**<font color="red"> [start:end] => start 이상 end 미만** 

In [5]:
a[1:5]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### 2> step

**<font color="red"> [start:end:step] => start 이상 end 미만(step 만큼 증가)** 

In [6]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

아래 ndarray를 slicing 하고 싶다.

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

#### cf> 하지만 행과 열을 동시에 slicing 불가능

In [7]:
a[3:6][3:6]

array([], shape=(0, 6), dtype=int32)

In [8]:
a[3:6] [3:6]

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

-------

## 2. Numpy 기본

**<font color="red"> 쉼표(,) 사용 가능**

In [9]:
A = [[1,2,3,4,5], [6,7,8,9,10]]
A 

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [10]:
A[0][1]

2

In [11]:
A[0,1] # python에서는 사용 불가

TypeError: list indices must be integers or slices, not tuple

하지만 numpy는 이런 상황에서도 가능합니다.

그래서 numpy의 장점 

1) 빠르다.(내부 구조가 C로 되어있어서 / for문 안 쓰게 해서) 

2) 편하다. (이렇게 많은 기능이 제공됩니다.) / 하지만 기능이 많다보니 중복되는 case들 (*와 np.multiply) 

### 1) Indexing

In [13]:
a[3,5] #== a[3][5]

True

### 2) Slicing

In [14]:
a[3:6, 3:6]

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [15]:
a[2:6:2, 3:6]

array([[15, 16, 17],
       [27, 28, 29]])

아까 안 되던 것도 가능합니다.

-------

## 3. Fancy Indexing

1> 내가 indexing한 부분들만 뽑아서 다시 이어주는 것 (discrete O) / 슬라이싱처럼 연속된 구간을 뽑아내는 것이 아니라 (continous X)

2> 대괄호 안에 또 대괄호를 넣는 방식으로 구현

### 1) Fancy Indexing 기본

In [17]:
#a[2,5]
a[[2,5]]

array([[12, 13, 14, 15, 16, 17],
       [30, 31, 32, 33, 34, 35]])

### 2) Fancy Indexing 응용

In [18]:
a[[2,5], [2,5]] # a[2,2]와 a[5,5]를 indexing 하는 것과 같다.

array([14, 35])

-----

아래 부분은 많이 어려운 내용입니다. 

여러분들에게 필수적으로 필요한 내용은 아니니 궁금하신 분들만 보시고 질문 받는 식으로 진행하겠습니다.

위의 fancy indexing과 유사합니다.

## 4. boolean Indexing (Masking)

### 1) boolean Indexing 1D

In [ ]:
boolean_1d = [True, True, False, False, True, True]

In [ ]:
a[boolean_1d]

### 2) boolean Indexing 2D

In [ ]:
boolean_2d = [True, True, False, False, True, True], [True, True, False, False, True, True]

a[boolean_2d]

In [ ]:
boolean_2d_tuple = ([True, True, False, False, True, True], 
                     [True, True, False, False, True, True])

a[boolean_2d_tuple]

In [ ]:
a = np.arange(6).reshape(2,3)
a[[True,False],[True,False,True]]