In [1]:
import numpy as np

# 0. hyperparameter 상수화

#### hyperparamter 자주 바꾸게 되므로 python에는 상수라는 개념이 없지만 C처럼 맨 위에 상수처럼 선언하고 진행

#### (다른 kernel들을 보면 대문자로 맨 위에서 선언하고 진행하는 경우가 많습니다.)

max_features = 사용할 단어의 최대 개수

max_len = 문장의 최대 길이

embedding_dims = 단어 vector 내부의 원소 개수

In [2]:
max_features = 20000

max_len = 200 # time_step
embedding_dims = 50 # feature

-----------

# 1. data upload

In [3]:
from tensorflow.keras.datasets import imdb

## 1) data upload

In [4]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

<__array_function__ internals>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
C:\Users\User\anaconda3\lib\site-packages\tensorflow\python\keras\datasets\imdb.py:159: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
C:\Users\User\anaconda3\lib\site-packages\tensorflow\python\keras\datasets\imdb.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant t

## 2) data에 대한 파악 - X

In [5]:
x_train.shape

(25000,)

In [6]:
print('train data가 ' + str(len(x_train)) +'개')

train data가 25000개


text

딥러닝 모델은 숫자를 받습니다.

text -> index ->(embedding) -> vector

그럼 data 내부는 어떻게 구성되어 있는가?

원래는 text(문자 data) 자체를 vector로 변환하는 작업 필요하지만 NLP를 자세히 다루는 시간이 아니기 때문에 

숫자(vector) 형태의 data를 보게 됩니다.

In [7]:
x_train # 25000개

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 82

25000개의 문장이 x_train에 담겨있다.

그럼 그 문장은 어떻게 생겼는가?

In [8]:
print(x_train[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [9]:
len(x_train[0])

218

In [10]:
len(x_train[1])

189

각 문장의 길이가 다르다는 문제가 생김

## 3) data에 대한 파악 - y

In [11]:
y_train.shape

(25000,)

In [12]:
print('역시 train data가 ' + str(len(y_train)) +'개')

역시 train data가 25000개


그 값은 어떻게 구성이 되어있는가?

In [13]:
y_train

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

0과 1이니 왠지 binary classfication? 

하지만 확인이 필요합니다.

In [14]:
np.unique(y_train)

array([0, 1], dtype=int64)

0과 1로만 구성이 되어있으므로 binary classification 맞습니다. (긍정 리뷰와 부정 리뷰 구분)

------

# 2. data preprocess

**오늘은 다른 전처리는 생략하고 진행하겠습니다.**

In [15]:
print(x_train[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


아까 문장의 길이가 각각 다르므로 진행해야하는 것은 문장의 길이를 통일하는 방법

(이미지도 그렇고 전처리의 핵심 중 하나는 data의 형태를 동일하게 해주어야 합니다.)

--- 다시

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [17]:
x_train = pad_sequences(x_train, maxlen=max_len)
x_test = pad_sequences(x_test, maxlen=max_len)

In [18]:
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)

x_train shape: (25000, 200)
x_test shape: (25000, 200)


In [19]:
x_train[0]

array([    5,    25,   100,    43,   838,   112,    50,   670,     2,
           9,    35,   480,   284,     5,   150,     4,   172,   112,
         167,     2,   336,   385,    39,     4,   172,  4536,  1111,
          17,   546,    38,    13,   447,     4,   192,    50,    16,
           6,   147,  2025,    19,    14,    22,     4,  1920,  4613,
         469,     4,    22,    71,    87,    12,    16,    43,   530,
          38,    76,    15,    13,  1247,     4,    22,    17,   515,
          17,    12,    16,   626,    18, 19193,     5,    62,   386,
          12,     8,   316,     8,   106,     5,     4,  2223,  5244,
          16,   480,    66,  3785,    33,     4,   130,    12,    16,
          38,   619,     5,    25,   124,    51,    36,   135,    48,
          25,  1415,    33,     6,    22,    12,   215,    28,    77,
          52,     5,    14,   407,    16,    82, 10311,     8,     4,
         107,   117,  5952,    15,   256,     4,     2,     7,  3766,
           5,   723,

------

### cf> input에 대한 이야기

현재 train_x.shape = (25000, 200)

우리가 RNN 모델에 넣어야 할 data의 ndim = 3 (25000, 200, input_dim)

즉, 단어를 vetor로 바꾸는 과정이 남았습니다.

### 정리

#### <font color="blue"> 1> 한 문장당 단어 = max_len(200)개

(이 단어 각각을 또 vector로 만든다.) 

#### <font color="blue"> 2> 이 단어 각각 vector의 원소 개수 = embedding_dims(50)개
    
(이 역할을 Embedding layer에서 진행)

# 3. build the model

simpleRNN 

- return_sequence = False => 2d array
- return_sequence = True => 3d array

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, SimpleRNN

In [21]:
def create_model():
    model = Sequential()
    # 2d_array (data, max_len)
    model.add(Embedding(max_features, embedding_dims, input_length=max_len))
    # 3d_array (data, max_len, embedding_dims)
    model.add(SimpleRNN(32))
    # 2d_array (data, value)
    model.add(Dense(1, activation='sigmoid'))
    # 1d_array [0, 1, 0, 0, 1]
    
    model.compile(optimizer = 'adam', metrics=['accuracy'], loss = 'binary_crossentropy')

    return model

In [22]:
model = create_model()

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 200, 50)           1000000   
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 32)                2656      
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 1,002,689
Trainable params: 1,002,689
Non-trainable params: 0
_________________________________________________________________


In [24]:
history = model.fit(x_train, y_train, validation_split=0.2, epochs=5, batch_size=512)

Epoch 1/5
40/40 [==============================] - 13s 288ms/step - loss: 0.6820 - accuracy: 0.5503 - val_loss: 0.5312 - val_accuracy: 0.7428
Epoch 2/5
40/40 [==============================] - 7s 163ms/step - loss: 0.4428 - accuracy: 0.8112 - val_loss: 0.3809 - val_accuracy: 0.8378
Epoch 3/5
40/40 [==============================] - 8s 191ms/step - loss: 0.2570 - accuracy: 0.9086 - val_loss: 0.3276 - val_accuracy: 0.8614
Epoch 4/5
40/40 [==============================] - 6s 158ms/step - loss: 0.1630 - accuracy: 0.9506 - val_loss: 0.3555 - val_accuracy: 0.8458
Epoch 5/5
40/40 [==============================] - 6s 141ms/step - loss: 0.1260 - accuracy: 0.9637 - val_loss: 0.3850 - val_accuracy: 0.8460


------

# 4. F1 score 사용

## 1) tensorflow의 metric을 사용

- tensorflow가 아직도 불안정한 면이 일부 있습니다. 잘 안 되는 분들은 2) 아래 예시로 하셔도 됩니다.

In [25]:
# 설치가 필요한 분들은 아래 tensorflow_addons를 설치해주세요.

#!pip install tensorflow_addons

In [26]:
from tensorflow.keras.metrics import Precision, Recall
from tensorflow_addons.metrics import F1Score

In [27]:
precision = Precision()
recall = Recall()
f1score = F1Score(num_classes=1, threshold=0.5)

용어 그대로라면 class가 2개인 binary classification이니까 num_class = 2로 설정하는 게 맞습니다.

하지만 tensorflow 내부에서 num_classes를 2로 설정하면 output layer의 node를 2개로 간주하면서 model train할 때 tensor 간의 shape이 맞지 않는 문제가 생깁니다.

그래서 binary classification에서만 예외적으로 num_classes를 1로 설정하면 됩니다.

In [28]:
def f1score_model():
    model = Sequential()
    # 2d_array (25000, 200)
    model.add(Embedding(max_features, embedding_dims, input_length=max_len))
    # 3d_array (25000, 200, 50)
    model.add(SimpleRNN(32, return_sequences = True)) # RNN의 output이 3d array가 됩니다.
    # 3d_array
    model.add(SimpleRNN(64))
    # 2d_array
    model.add(Dense(1, activation='sigmoid'))
    # 1d_array

    
    model.compile(optimizer = 'adam', metrics=['accuracy', precision, recall, f1score], loss = 'binary_crossentropy')

    return model

In [29]:
model_f = f1score_model()

In [30]:
history = model_f.fit(x_train, y_train, validation_split=0.2, epochs=5, batch_size=512)

Epoch 1/5
40/40 [==============================] - 21s 442ms/step - loss: 0.6762 - accuracy: 0.5580 - precision: 0.5556 - recall: 0.5839 - f1_score: 0.5693 - val_loss: 0.4476 - val_accuracy: 0.7970 - val_precision: 0.7595 - val_recall: 0.8619 - val_f1_score: 0.8074
Epoch 2/5
40/40 [==============================] - 14s 363ms/step - loss: 0.3277 - accuracy: 0.8637 - precision: 0.8591 - recall: 0.8753 - f1_score: 0.8668 - val_loss: 0.3675 - val_accuracy: 0.8666 - val_precision: 0.8460 - val_recall: 0.8923 - val_f1_score: 0.8685
Epoch 3/5
40/40 [==============================] - 13s 329ms/step - loss: 0.1529 - accuracy: 0.9475 - precision: 0.9480 - recall: 0.9459 - f1_score: 0.9470 - val_loss: 0.3741 - val_accuracy: 0.8558 - val_precision: 0.9130 - val_recall: 0.7825 - val_f1_score: 0.8427
Epoch 4/5
40/40 [==============================] - 16s 391ms/step - loss: 0.0814 - accuracy: 0.9763 - precision: 0.9788 - recall: 0.9735 - f1_score: 0.9761 - val_loss: 0.3917 - val_accuracy: 0.8442 - va

precision과 recall의 조화평균(2ab/(a+b))를 구하면 f1_score가 나오는 것을 확인할 수 있습니다.

## 2) custom metrics

In [31]:
from keras import backend as K

def recall_m(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

def precision_m(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision

def f1_m(y_true, y_pred):
    precision = precision_m(y_true, y_pred)
    recall = recall_m(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [32]:
def f1score_model():
    model = Sequential()
    # 2d_array (25000, 200)
    model.add(Embedding(max_features, embedding_dims, input_length=max_len))
    # 3d_array (25000, 200, 50)
    model.add(SimpleRNN(32, return_sequences = True)) # RNN의 output이 3d array가 됩니다.
    # 3d_array
    model.add(SimpleRNN(64))
    # 2d_array
    model.add(Dense(1, activation='sigmoid'))
    # 1d_array

    
    model.compile(optimizer = 'adam', metrics=['accuracy', recall_m, precision_m, f1_m], loss = 'binary_crossentropy')

    return model

In [33]:
model_f = f1score_model()

In [34]:
history = model_f.fit(x_train, y_train, validation_split=0.2, epochs=5, batch_size=512)

Epoch 1/5
40/40 [==============================] - 15s 304ms/step - loss: 0.6945 - accuracy: 0.5256 - recall_m: 0.5427 - precision_m: 0.5308 - f1_m: 0.5288 - val_loss: 0.5472 - val_accuracy: 0.7290 - val_recall_m: 0.6475 - val_precision_m: 0.7670 - val_f1_m: 0.7018
Epoch 2/5
40/40 [==============================] - 12s 292ms/step - loss: 0.4602 - accuracy: 0.7846 - recall_m: 0.7667 - precision_m: 0.8109 - f1_m: 0.7786 - val_loss: 0.3892 - val_accuracy: 0.8310 - val_recall_m: 0.9058 - val_precision_m: 0.7838 - val_f1_m: 0.8403
Epoch 3/5
40/40 [==============================] - 13s 319ms/step - loss: 0.2421 - accuracy: 0.9084 - recall_m: 0.9226 - precision_m: 0.8987 - f1_m: 0.9099 - val_loss: 0.3825 - val_accuracy: 0.8394 - val_recall_m: 0.7793 - val_precision_m: 0.8812 - val_f1_m: 0.8269
Epoch 4/5
40/40 [==============================] - 12s 308ms/step - loss: 0.1269 - accuracy: 0.9573 - recall_m: 0.9551 - precision_m: 0.9591 - f1_m: 0.9567 - val_loss: 0.4015 - val_accuracy: 0.8470 - va